### ISSUE TITLE
Outdated link in generator

### ISSUE THREAD

**Issue by collimarco** [heartcombo/simple_form#1755] opened 2022-01-12 16:35 UTC
Run:

```
rails generate simple_form:install --bootstrap
```

You get some outdated / broken links in the std output.

(e.g. http://simple-form-bootstrap.plataformatec.com.br/)

**Comment by m5o** [comment] 2022-01-15 16:05
Duplicate of #1737

Thank you for the report.

**Closed** 2022-01-23 18:19 UTC
