### ISSUE TITLE
https://simple-form-bootstrap.herokuapp.com/ is Down

### ISSUE THREAD

**Issue by ramaboo** [heartcombo/simple_form#1838] opened 2024-04-03 07:33 UTC
The README file contains a link to https://simple-form-bootstrap.herokuapp.com/ which seems broken.

**Comment by abinoam** [comment] 2024-04-24 21:57
There's already a PR to remove it #1820 by @JuanVqz

**Comment by nashby** [comment] 2024-06-25 18:17
Duplicate of https://github.com/heartcombo/simple_form/issues/1815

**Closed by nashby** 2024-06-25 18:17 UTC
