### ISSUE TITLE
Invalid or incomplete POST params => ActionController::RoutingError 

### ISSUE THREAD

**Issue by Tioneb12** [heartcombo/simple_form#1706] opened 2020-06-08 11:03 UTC
## Environment

- Ruby **2.6.5**
- Rails **6.0.2.1**
- Simple Form **5.0.2**

## Current behavior
I have scopes in my model :

```
scope :animals, -> { where(type_service: 'animals') }
scope :active, -> { where(active: true) }
```

The form return an error : Invalid or incomplete POST params and a RoutingError

**doesn't  works** with radio_buttons &  check_boxes
```
<%= poi.association :services, :as => :radio_buttons, :collection => Service.options_sheets %>
<%= poi.association :services, :as => :check_boxes, :collection => Service.animals.active %>
```
**works** with radio_buttons or check_boxes for the two fields
```
<%= poi.association :services, :as => :radio_buttons, :collection => Service.options_sheets %>
<%= poi.association :services, :as => :radio_buttons, :collection => Service.animals.active %>
```
**works**
```
<%= poi.association :services, :as => :check_boxes, :collection => Service.options_sheets %>
<%= poi.association :services, :as => :check_boxes, :collection => Service.animals.active %>
```
**doesn't  works** with select and check_boxes
```
<%= poi.association :services, :as => :select, :collection => Service.options_sheets %>
<%= poi.association :services, :as => :check_boxes, :collection => Service.animals.active %>
```
but ***works*** with the reverse
```
<%= poi.association :services, :as => :check_boxes, :collection => Service.options_sheets %>
<%= poi.association :services, :as => :select, :collection => Service.animals.active %>
```

**Comment by ramaboo** [comment] 2022-02-09 03:42
I am seeing the same thing with a similar setup. Any idea what the root cause might be?

**Comment by nashby** [comment] 2022-02-20 18:24
Hey! I'm closing this for now since there's no an easy way of reproducing it without simple app. Feel free to submit it so we can investigate.

**Closed by nashby** 2022-02-20 18:24 UTC
